import type { VendorHistoryOrder } from '../shared/vendorData/types'
import { buildVendorHistoryFromSource } from '../shared/vendorData/buildVendorHistoryFromSource'

/** Back-compat aliases for Optima-specific imports. */
export type { VendorHistoryLine as OptimaHistoryLine } from '../shared/vendorData/types'
export type { VendorHistoryOrder as OptimaHistoricalOrder } from '../shared/vendorData/types'

/**
 * Parsed from exported SMS/RCS “Optima Order” PDF (Mykos ↔ Optima).
 * `date` ≈ when the order message was sent; `deliveryDate` = Thursday in the thread.
 * Add-ons in the same week are merged into that Thursday’s order.
 */
const optimaMessageHistoryRaw: VendorHistoryOrder[] = [
  {
    date: '2025-11-23',
    deliveryDate: '2025-11-25',
    items: [
      { itemId: 'honey-monastiri-crete', quantity: '1', unitType: 'case' },
      { itemId: 'yogurt-triple-cream', quantity: '6', unitType: 'each' },
      { itemId: 'kefalograviera', quantity: '1', unitType: 'wheel' },
      { itemId: 'sour-cherries-pella', quantity: '1', unitType: 'case' },
      { itemId: 'water-still', quantity: '2', unitType: 'case' },
      { itemId: 'water-sparkling', quantity: '7', unitType: 'case' },
    ],
  },
  {
    date: '2025-12-08',
    deliveryDate: '2025-12-10',
    items: [
      { itemId: 'honey-monastiri-crete', quantity: '1', unitType: 'case' },
      { itemId: 'kefalograviera', quantity: '1', unitType: 'wheel' },
      { itemId: 'yogurt-triple-cream', quantity: '4', unitType: 'each' },
      {
        itemId: 'spanakopita-domnas-2x12',
        quantity: '1',
        unitType: 'case',
        packSizeSnapshot: '2x12',
      },
      {
        itemId: 'evoo-iliada-4x3',
        quantity: '1',
        unitType: 'case',
        packSizeSnapshot: '4x3',
      },
      { itemId: 'feta-epiros', quantity: '1', unitType: 'tub' },
    ],
  },
  {
    date: '2025-12-15',
    deliveryDate: '2025-12-18',
    items: [
      { itemId: 'honey-monastiri-crete', quantity: '1', unitType: 'case' },
      { itemId: 'sour-cherries-pella', quantity: '1', unitType: 'case' },
      { itemId: 'yogurt-triple-cream', quantity: '7', unitType: 'each' },
      {
        itemId: 'spanakopita-domnas-2x12',
        quantity: '3',
        unitType: 'case',
        packSizeSnapshot: '2x12',
      },
      {
        itemId: 'spanakopita-domnas-2x40',
        quantity: '2',
        unitType: 'case',
        packSizeSnapshot: '2x40',
      },
      { itemId: 'water-sparkling', quantity: '7', unitType: 'case' },
    ],
  },
  {
    date: '2025-12-21',
    deliveryDate: '2025-12-23',
    items: [
      { itemId: 'honey-monastiri-crete', quantity: '1', unitType: 'case' },
      { itemId: 'yogurt-triple-cream', quantity: '6', unitType: 'each' },
      {
        itemId: 'spanakopita-domnas-2x12',
        quantity: '1',
        unitType: 'case',
        packSizeSnapshot: '2x12',
      },
      { itemId: 'oregano-dried-etaygetos', quantity: '1', unitType: 'case' },
      { itemId: 'kefalograviera', quantity: '1', unitType: 'wheel' },
    ],
  },
  {
    date: '2025-12-28',
    deliveryDate: '2025-12-30',
    items: [
      { itemId: 'yogurt-triple-cream', quantity: '6', unitType: 'each' },
      { itemId: 'kefalograviera', quantity: '1', unitType: 'wheel' },
      { itemId: 'sour-cherries-pella', quantity: '1', unitType: 'case' },
      { itemId: 'water-sparkling', quantity: '4', unitType: 'case' },
      { itemId: 'water-still', quantity: '4', unitType: 'case' },
    ],
  },
  {
    date: '2026-01-04',
    deliveryDate: '2026-01-08',
    items: [
      { itemId: 'honey-monastiri-crete', quantity: '1', unitType: 'case' },
      { itemId: 'yogurt-triple-cream', quantity: '6', unitType: 'each' },
      { itemId: 'cod-roe-big-bag', quantity: '1', unitType: 'case' },
      { itemId: 'fillo-zimi', quantity: '1', unitType: 'case' },
      { itemId: 'water-sparkling', quantity: '5', unitType: 'case' },
      { itemId: 'water-still', quantity: '4', unitType: 'case' },
    ],
  },
  {
    date: '2026-01-11',
    deliveryDate: '2026-01-15',
    items: [
      { itemId: 'honey-monastiri-crete', quantity: '1', unitType: 'case' },
      { itemId: 'beans-voion-giant', quantity: '1', unitType: 'case' },
      { itemId: 'oregano-dried-etaygetos', quantity: '1', unitType: 'case' },
      { itemId: 'orzo-misko', quantity: '1', unitType: 'bag' },
      { itemId: 'kefalograviera', quantity: '1', unitType: 'wheel' },
      { itemId: 'sour-cherries-pella', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2026-01-18',
    deliveryDate: '2026-01-22',
    items: [
      { itemId: 'honey-monastiri-crete', quantity: '1', unitType: 'case' },
      { itemId: 'kefalograviera', quantity: '1', unitType: 'wheel' },
      { itemId: 'sour-cherries-pella', quantity: '1', unitType: 'case' },
      {
        itemId: 'spanakopita-domnas-2x12',
        quantity: '2',
        unitType: 'case',
        packSizeSnapshot: '2x12',
      },
      {
        itemId: 'spanakopita-domnas-2x40',
        quantity: '1',
        unitType: 'case',
        packSizeSnapshot: '2x40',
      },
      { itemId: 'yogurt-triple-cream', quantity: '10', unitType: 'each' },
      { itemId: 'water-sparkling', quantity: '5', unitType: 'case' },
      { itemId: 'water-still', quantity: '6', unitType: 'case' },
      {
        itemId: 'evoo-iliada-4x3',
        quantity: '1',
        unitType: 'case',
        packSizeSnapshot: '4x3',
      },
      { itemId: 'feta-epiros', quantity: '1', unitType: 'tub' },
      { itemId: 'manouri-hotos', quantity: '1', unitType: 'tub' },
      { itemId: 'fillo-zimi', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2026-01-24',
    deliveryDate: '2026-01-29',
    items: [
      { itemId: 'honey-monastiri-crete', quantity: '1', unitType: 'case' },
      { itemId: 'yogurt-triple-cream', quantity: '5', unitType: 'each' },
      { itemId: 'fillo-zimi', quantity: '1', unitType: 'case' },
      { itemId: 'water-sparkling', quantity: '5', unitType: 'case' },
      { itemId: 'water-still', quantity: '5', unitType: 'case' },
      {
        itemId: 'evoo-iliada-4x3',
        quantity: '1',
        unitType: 'case',
        packSizeSnapshot: '4x3',
      },
      { itemId: 'feta-epiros', quantity: '1', unitType: 'tub' },
      { itemId: 'kefalograviera', quantity: '1', unitType: 'wheel' },
      { itemId: 'sour-cherries-pella', quantity: '1', unitType: 'case' },
      { itemId: 'halloumi-cypriana', quantity: '1', unitType: 'case' },
      { itemId: 'kalamata-olives-pitted', quantity: '2', unitType: 'tub' },
      {
        itemId: 'spanakopita-domnas-2x12',
        quantity: '1',
        unitType: 'case',
        packSizeSnapshot: '2x12',
      },
    ],
  },
  {
    date: '2026-02-04',
    deliveryDate: '2026-02-05',
    items: [
      { itemId: 'honey-monastiri-crete', quantity: '2', unitType: 'case' },
      { itemId: 'yogurt-triple-cream', quantity: '6', unitType: 'each' },
      { itemId: 'water-sparkling', quantity: '10', unitType: 'case' },
      { itemId: 'water-still', quantity: '15', unitType: 'case' },
      { itemId: 'oregano-dried-etaygetos', quantity: '1', unitType: 'case' },
      {
        itemId: 'evoo-iliada-4x3',
        quantity: '1',
        unitType: 'case',
        packSizeSnapshot: '4x3',
      },
      { itemId: 'feta-epiros', quantity: '2', unitType: 'tub' },
      { itemId: 'orzo-misko', quantity: '1', unitType: 'bag' },
      { itemId: 'sour-cherries-pella', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2026-02-08',
    deliveryDate: '2026-02-12',
    items: [
      { itemId: 'honey-monastiri-crete', quantity: '1', unitType: 'case' },
      { itemId: 'beans-voion-giant', quantity: '1', unitType: 'case' },
      { itemId: 'yogurt-triple-cream', quantity: '10', unitType: 'each' },
      { itemId: 'water-sparkling', quantity: '5', unitType: 'case' },
      { itemId: 'water-still', quantity: '5', unitType: 'case' },
      {
        itemId: 'evoo-iliada-4x3',
        quantity: '2',
        unitType: 'case',
        packSizeSnapshot: '4x3',
      },
      { itemId: 'kefalograviera', quantity: '1', unitType: 'wheel' },
      { itemId: 'feta-epiros', quantity: '2', unitType: 'tub' },
      { itemId: 'sour-cherries-pella', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2026-02-15',
    deliveryDate: '2026-02-19',
    items: [
      { itemId: 'honey-monastiri-crete', quantity: '1', unitType: 'case' },
      { itemId: 'beans-voion-giant', quantity: '1', unitType: 'case' },
      { itemId: 'yogurt-triple-cream', quantity: '10', unitType: 'each' },
      { itemId: 'water-sparkling', quantity: '6', unitType: 'case' },
      { itemId: 'water-still', quantity: '5', unitType: 'case' },
      {
        itemId: 'evoo-iliada-4x3',
        quantity: '2',
        unitType: 'case',
        packSizeSnapshot: '4x3',
      },
      { itemId: 'kefalograviera', quantity: '1', unitType: 'wheel' },
      { itemId: 'sour-cherries-pella', quantity: '1', unitType: 'case' },
      { itemId: 'fillo-zimi', quantity: '2', unitType: 'case' },
      { itemId: 'oregano-dried-etaygetos', quantity: '1', unitType: 'case' },
      { itemId: 'kalamata-olives-pitted', quantity: '1', unitType: 'tub' },
    ],
  },
  {
    date: '2026-02-22',
    deliveryDate: '2026-02-26',
    items: [
      { itemId: 'yogurt-triple-cream', quantity: '10', unitType: 'each' },
      { itemId: 'water-sparkling', quantity: '12', unitType: 'case' },
      { itemId: 'water-still', quantity: '7', unitType: 'case' },
      {
        itemId: 'evoo-iliada-4x3',
        quantity: '2',
        unitType: 'case',
        packSizeSnapshot: '4x3',
      },
      { itemId: 'sour-cherries-pella', quantity: '1', unitType: 'case' },
      { itemId: 'orzo-misko', quantity: '1', unitType: 'bag' },
      { itemId: 'feta-epiros', quantity: '2', unitType: 'tub' },
      { itemId: 'honey-monastiri-crete', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2026-03-01',
    deliveryDate: '2026-03-05',
    items: [
      { itemId: 'yogurt-triple-cream', quantity: '5', unitType: 'each' },
      { itemId: 'water-sparkling', quantity: '6', unitType: 'case' },
      { itemId: 'water-still', quantity: '6', unitType: 'case' },
      {
        itemId: 'evoo-iliada-4x3',
        quantity: '1',
        unitType: 'case',
        packSizeSnapshot: '4x3',
      },
      { itemId: 'feta-epiros', quantity: '2', unitType: 'tub' },
      { itemId: 'oregano-dried-etaygetos', quantity: '1', unitType: 'case' },
      { itemId: 'kefalograviera', quantity: '1', unitType: 'wheel' },
      { itemId: 'honey-monastiri-crete', quantity: '1', unitType: 'case' },
      { itemId: 'fillo-zimi', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2026-03-08',
    deliveryDate: '2026-03-12',
    items: [
      { itemId: 'yogurt-triple-cream', quantity: '5', unitType: 'each' },
      { itemId: 'water-sparkling', quantity: '4', unitType: 'case' },
      { itemId: 'water-still', quantity: '6', unitType: 'case' },
      {
        itemId: 'evoo-iliada-4x3',
        quantity: '1',
        unitType: 'case',
        packSizeSnapshot: '4x3',
      },
      { itemId: 'feta-epiros', quantity: '1', unitType: 'tub' },
      { itemId: 'kefalograviera', quantity: '1', unitType: 'wheel' },
      { itemId: 'honey-monastiri-crete', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2026-03-15',
    deliveryDate: '2026-03-19',
    items: [
      { itemId: 'beans-voion-giant', quantity: '1', unitType: 'case' },
      { itemId: 'fillo-zimi', quantity: '1', unitType: 'case' },
      { itemId: 'manouri-hotos', quantity: '1', unitType: 'tub' },
      { itemId: 'orzo-misko', quantity: '1', unitType: 'bag' },
      { itemId: 'yogurt-triple-cream', quantity: '6', unitType: 'each' },
      { itemId: 'water-sparkling', quantity: '10', unitType: 'case' },
      { itemId: 'water-still', quantity: '5', unitType: 'case' },
      {
        itemId: 'evoo-iliada-4x3',
        quantity: '2',
        unitType: 'case',
        packSizeSnapshot: '4x3',
      },
      { itemId: 'feta-epiros', quantity: '2', unitType: 'tub' },
      { itemId: 'kefalograviera', quantity: '1', unitType: 'wheel' },
      { itemId: 'honey-monastiri-crete', quantity: '1', unitType: 'case' },
      { itemId: 'sour-cherries-pella', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2026-03-22',
    deliveryDate: '2026-03-26',
    items: [
      { itemId: 'manouri-hotos', quantity: '1', unitType: 'tub' },
      { itemId: 'halloumi-cypriana', quantity: '1', unitType: 'case' },
      { itemId: 'yogurt-triple-cream', quantity: '6', unitType: 'each' },
      { itemId: 'water-sparkling', quantity: '3', unitType: 'case' },
      { itemId: 'water-still', quantity: '8', unitType: 'case' },
      {
        itemId: 'evoo-iliada-4x3',
        quantity: '2',
        unitType: 'case',
        packSizeSnapshot: '4x3',
      },
      { itemId: 'oregano-dried-etaygetos', quantity: '1', unitType: 'case' },
      { itemId: 'feta-epiros', quantity: '3', unitType: 'tub' },
      { itemId: 'kefalograviera', quantity: '1', unitType: 'wheel' },
      { itemId: 'honey-monastiri-crete', quantity: '2', unitType: 'case' },
      { itemId: 'sour-cherries-pella', quantity: '1', unitType: 'case' },
      { itemId: 'cod-roe-big-bag', quantity: '1', unitType: 'case' },
      { itemId: 'kalamata-olives-pitted', quantity: '1', unitType: 'tub' },
    ],
  },
  {
    date: '2026-03-29',
    deliveryDate: '2026-04-02',
    items: [
      { itemId: 'yogurt-triple-cream', quantity: '6', unitType: 'each' },
      { itemId: 'water-sparkling', quantity: '8', unitType: 'case' },
      { itemId: 'water-still', quantity: '2', unitType: 'case' },
      {
        itemId: 'evoo-iliada-4x3',
        quantity: '1',
        unitType: 'case',
        packSizeSnapshot: '4x3',
      },
      { itemId: 'feta-epiros', quantity: '3', unitType: 'tub' },
      { itemId: 'kefalograviera', quantity: '1', unitType: 'wheel' },
      { itemId: 'honey-monastiri-crete', quantity: '1', unitType: 'case' },
      { itemId: 'sour-cherries-pella', quantity: '1', unitType: 'case' },
    ],
  },
]

export const optimaSeedHistory = buildVendorHistoryFromSource('optima', {
  kind: 'structured_orders',
  orders: optimaMessageHistoryRaw,
})
