import type { VendorHistoryOrder } from '../shared/vendorData/types'
import { buildVendorHistoryFromSource } from '../shared/vendorData/buildVendorHistoryFromSource'

const aceEndicoMessageHistoryRaw: VendorHistoryOrder[] = [
  {
    date: '2025-08-18',
    deliveryDate: '2025-08-20',
    items: [
      { itemId: 'salt-kosher-crystal-diamond', quantity: '1', unitType: 'case' },
      { itemId: 'fryer-oil-olitalia', quantity: '3', unitType: 'case' },
      { itemId: 'nuts-pistachio', quantity: '4', unitType: '#' },
      { itemId: 'penne', quantity: '1', unitType: 'bag' },
      { itemId: 'rice-basmati', quantity: '1', unitType: 'bag' },
      { itemId: 'spice-coriander-seeds', quantity: '1', unitType: 'pc' },
      { itemId: 'spice-garlic-powder', quantity: '1', unitType: 'pc' },
      { itemId: 'vinegar-champagne', quantity: '1', unitType: 'pc' },
      { itemId: 'vinegar-cider', quantity: '1', unitType: 'pc' },
      { itemId: 'vinegar-red-wine', quantity: '1', unitType: 'pc' },
      { itemId: 'milk-whole', quantity: '8', unitType: 'gallon' },
      { itemId: 'heavy-cream', quantity: '1', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '1', unitType: 'case' },
      { itemId: 'mascarpone', quantity: '1', unitType: 'case' },
      { itemId: 'buttermilk', quantity: '2', unitType: 'pc' },
      { itemId: 'eggs-pasteurized', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2025-08-25',
    deliveryDate: '2025-08-27',
    items: [
      { itemId: 'fryer-oil-olitalia', quantity: '3', unitType: 'case' },
      { itemId: 'milk-whole', quantity: '3', unitType: 'gallon' },
      { itemId: 'heavy-cream', quantity: '1', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '1', unitType: 'case' },
      { itemId: 'mascarpone', quantity: '1', unitType: 'case' },
      { itemId: 'buttermilk', quantity: '2', unitType: 'pc' },
      { itemId: 'eggs-pasteurized', quantity: '2', unitType: 'case' },
      { itemId: 'flour-00', quantity: '1', unitType: 'bag' },
      { itemId: 'chocolate-callebaut-milk', quantity: '1', unitType: 'bag' },
      { itemId: 'cornstarch', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2025-09-01',
    deliveryDate: '2025-09-03',
    items: [
      { itemId: 'fryer-oil-olitalia', quantity: '4', unitType: 'case' },
      { itemId: 'milk-whole', quantity: '6', unitType: 'gallon' },
      { itemId: 'heavy-cream', quantity: '1', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '1', unitType: 'case' },
      { itemId: 'mascarpone', quantity: '1', unitType: 'case' },
      { itemId: 'buttermilk', quantity: '2', unitType: 'pc' },
      { itemId: 'eggs-pasteurized', quantity: '1', unitType: 'case' },
      { itemId: 'flour-00', quantity: '1', unitType: 'bag' },
      { itemId: 'flour-durum', quantity: '1', unitType: 'bag' },
      { itemId: 'nuts-walnuts', quantity: '4', unitType: '#' },
      { itemId: 'nuts-pistachio', quantity: '8', unitType: '#' },
      { itemId: 'spice-black-pepper-whole', quantity: '2', unitType: 'pc' },
      { itemId: 'spice-cumin-seeds', quantity: '1', unitType: 'pc' },
      { itemId: 'spice-coriander-seeds', quantity: '2', unitType: 'pc' },
      { itemId: 'salt-kosher-crystal-diamond', quantity: '1', unitType: 'case' },
      { itemId: 'salt-maldon', quantity: '1', unitType: 'tub' },
      { itemId: 'pan-spray', quantity: '1', unitType: 'case' },
      { itemId: 'penne', quantity: '1', unitType: 'bag' },
    ],
  },
  {
    date: '2025-09-08',
    deliveryDate: '2025-09-10',
    items: [
      { itemId: 'fryer-oil-olitalia', quantity: '3', unitType: 'case' },
      { itemId: 'milk-whole', quantity: '4', unitType: 'gallon' },
      { itemId: 'heavy-cream', quantity: '1', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '1', unitType: 'case' },
      { itemId: 'mascarpone', quantity: '1', unitType: 'case' },
      { itemId: 'buttermilk', quantity: '2', unitType: 'pc' },
      { itemId: 'eggs-pasteurized', quantity: '1', unitType: 'case' },
      { itemId: 'flour-00', quantity: '1', unitType: 'bag' },
      { itemId: 'nuts-walnuts', quantity: '4', unitType: '#' },
      { itemId: 'nuts-pistachio', quantity: '4', unitType: '#' },
      { itemId: 'cocoa-powder', quantity: '1', unitType: 'case' },
      { itemId: 'cornstarch', quantity: '1', unitType: 'case' },
      { itemId: 'spice-cinnamon-sticks', quantity: '2', unitType: 'pc' },
      { itemId: 'spice-fennel-seed', quantity: '1', unitType: 'pc' },
      { itemId: 'spice-garlic-powder', quantity: '1', unitType: 'pc' },
      { itemId: 'sugar-granulated', quantity: '1', unitType: 'bag' },
      { itemId: 'canola-oil', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2025-09-15',
    deliveryDate: '2025-09-17',
    items: [
      { itemId: 'flour-00', quantity: '1', unitType: 'bag' },
      { itemId: 'flour-durum', quantity: '1', unitType: 'bag' },
      { itemId: 'fryer-oil-olitalia', quantity: '3', unitType: 'case' },
      { itemId: 'mustard-dijon', quantity: '1', unitType: 'tub' },
      { itemId: 'nuts-pistachio', quantity: '4', unitType: '#' },
      { itemId: 'salt-kosher-crystal-diamond', quantity: '1', unitType: 'case' },
      { itemId: 'spice-cumin-seeds', quantity: '1', unitType: 'pc' },
      { itemId: 'milk-whole', quantity: '8', unitType: 'gallon' },
      { itemId: 'heavy-cream', quantity: '1', unitType: 'case' },
      { itemId: 'buttermilk', quantity: '2', unitType: 'pc' },
      { itemId: 'eggs-pasteurized', quantity: '2', unitType: 'case' },
    ],
  },
  {
    date: '2025-09-22',
    deliveryDate: '2025-09-24',
    items: [
      { itemId: 'flour-00', quantity: '1', unitType: 'bag' },
      { itemId: 'flour-durum', quantity: '1', unitType: 'bag' },
      { itemId: 'fryer-oil-olitalia', quantity: '3', unitType: 'case' },
      { itemId: 'milk-whole', quantity: '4', unitType: 'gallon' },
      { itemId: 'heavy-cream', quantity: '1', unitType: 'case' },
      { itemId: 'buttermilk', quantity: '2', unitType: 'pc' },
      { itemId: 'eggs-pasteurized', quantity: '2', unitType: 'case' },
      { itemId: 'penne', quantity: '1', unitType: 'bag' },
      { itemId: 'rice-basmati', quantity: '1', unitType: 'bag' },
      { itemId: 'mascarpone', quantity: '1', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '1', unitType: 'case' },
      { itemId: 'chickpeas-dried', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2025-09-29',
    deliveryDate: '2025-10-01',
    items: [
      { itemId: 'flour-00', quantity: '1', unitType: 'bag' },
      { itemId: 'flour-durum', quantity: '1', unitType: 'bag' },
      { itemId: 'sugar-granulated', quantity: '1', unitType: 'bag' },
      { itemId: 'fryer-oil-olitalia', quantity: '3', unitType: 'case' },
      { itemId: 'milk-whole', quantity: '7', unitType: 'gallon' },
      { itemId: 'heavy-cream', quantity: '1', unitType: 'case' },
      { itemId: 'buttermilk', quantity: '2', unitType: 'pc' },
      { itemId: 'eggs-pasteurized', quantity: '1', unitType: 'case' },
      { itemId: 'mascarpone', quantity: '1', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '1', unitType: 'case' },
      { itemId: 'nuts-pistachio', quantity: '4', unitType: '#' },
      { itemId: 'nuts-hazelnuts', quantity: '4', unitType: '#' },
      { itemId: 'salt-kosher-crystal-diamond', quantity: '1', unitType: 'case' },
      { itemId: 'pan-spray', quantity: '1', unitType: 'case' },
      { itemId: 'spice-cinnamon-sticks', quantity: '6', unitType: 'pc' },
      { itemId: 'spice-black-pepper-whole', quantity: '2', unitType: 'pc' },
      { itemId: 'sugar-confectioners-10x', quantity: '1', unitType: 'case' },
      { itemId: 'tomato-paste-mutti', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2025-10-06',
    deliveryDate: '2025-10-08',
    items: [
      { itemId: 'flour-durum', quantity: '1', unitType: 'bag' },
      { itemId: 'fryer-oil-olitalia', quantity: '4', unitType: 'case' },
      { itemId: 'milk-whole', quantity: '3', unitType: 'gallon' },
      { itemId: 'heavy-cream', quantity: '1', unitType: 'case' },
      { itemId: 'buttermilk', quantity: '2', unitType: 'pc' },
      { itemId: 'eggs-pasteurized', quantity: '2', unitType: 'case' },
      { itemId: 'mascarpone', quantity: '1', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '1', unitType: 'case' },
      { itemId: 'nuts-pistachio', quantity: '4', unitType: '#' },
      { itemId: 'sugar-confectioners-10x', quantity: '1', unitType: 'case' },
      { itemId: 'penne', quantity: '1', unitType: 'bag' },
      { itemId: 'salt-kosher-crystal-diamond', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2025-10-13',
    deliveryDate: '2025-10-15',
    items: [
      { itemId: 'flour-00', quantity: '1', unitType: 'bag' },
      { itemId: 'milk-whole', quantity: '4', unitType: 'gallon' },
      { itemId: 'heavy-cream', quantity: '1', unitType: 'case' },
      { itemId: 'buttermilk', quantity: '2', unitType: 'pc' },
      { itemId: 'eggs-pasteurized', quantity: '1', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '1', unitType: 'case' },
      { itemId: 'panko', quantity: '1', unitType: 'bag' },
      { itemId: 'salt-maldon', quantity: '1', unitType: 'tub' },
    ],
  },
  {
    date: '2025-10-20',
    deliveryDate: '2025-10-22',
    items: [
      { itemId: 'flour-durum', quantity: '1', unitType: 'bag' },
      { itemId: 'flour-00', quantity: '1', unitType: 'bag' },
      { itemId: 'chickpeas-dried', quantity: '1', unitType: 'case' },
      { itemId: 'sugar-granulated', quantity: '1', unitType: 'bag' },
      { itemId: 'fryer-oil-olitalia', quantity: '3', unitType: 'case' },
      { itemId: 'canola-oil', quantity: '1', unitType: 'case' },
      { itemId: 'cornstarch', quantity: '1', unitType: 'case' },
      { itemId: 'milk-whole', quantity: '6', unitType: 'gallon' },
      { itemId: 'heavy-cream', quantity: '1', unitType: 'case' },
      { itemId: 'eggs-pasteurized', quantity: '2', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '1', unitType: 'case' },
      { itemId: 'nuts-pistachio', quantity: '4', unitType: '#' },
      { itemId: 'nuts-walnuts', quantity: '4', unitType: '#' },
    ],
  },
  {
    date: '2025-10-27',
    deliveryDate: '2025-10-29',
    items: [
      { itemId: 'flour-00', quantity: '1', unitType: 'bag' },
      { itemId: 'flour-durum', quantity: '1', unitType: 'bag' },
      { itemId: 'fryer-oil-olitalia', quantity: '3', unitType: 'case' },
      { itemId: 'penne', quantity: '1', unitType: 'bag' },
      { itemId: 'rice-basmati', quantity: '1', unitType: 'bag' },
      { itemId: 'salt-kosher-crystal-diamond', quantity: '1', unitType: 'case' },
      { itemId: 'spice-black-pepper-whole', quantity: '2', unitType: 'pc' },
      { itemId: 'mascarpone', quantity: '1', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '1', unitType: 'case' },
      { itemId: 'milk-whole', quantity: '4', unitType: 'gallon' },
      { itemId: 'heavy-cream', quantity: '1', unitType: 'case' },
      { itemId: 'buttermilk', quantity: '2', unitType: 'pc' },
      { itemId: 'eggs-pasteurized', quantity: '1', unitType: 'case' },
      { itemId: 'tomato-paste-mutti', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2025-11-03',
    deliveryDate: '2025-11-05',
    items: [
      { itemId: 'flour-00', quantity: '1', unitType: 'bag' },
      { itemId: 'sugar-granulated', quantity: '1', unitType: 'bag' },
      { itemId: 'fryer-oil-olitalia', quantity: '2', unitType: 'case' },
      { itemId: 'nuts-pistachio', quantity: '4', unitType: '#' },
      { itemId: 'penne', quantity: '1', unitType: 'bag' },
      { itemId: 'salt-kosher-crystal-diamond', quantity: '1', unitType: 'case' },
      { itemId: 'spice-black-pepper-whole', quantity: '1', unitType: 'pc' },
      { itemId: 'mascarpone', quantity: '1', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '1', unitType: 'case' },
      { itemId: 'milk-whole', quantity: '8', unitType: 'gallon' },
      { itemId: 'heavy-cream', quantity: '1', unitType: 'case' },
      { itemId: 'buttermilk', quantity: '2', unitType: 'pc' },
      { itemId: 'eggs-pasteurized', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2025-11-10',
    deliveryDate: '2025-11-12',
    items: [
      { itemId: 'flour-00', quantity: '1', unitType: 'bag' },
      { itemId: 'sugar-granulated', quantity: '1', unitType: 'bag' },
      { itemId: 'flour-durum', quantity: '1', unitType: 'bag' },
      { itemId: 'cornstarch', quantity: '1', unitType: 'case' },
      { itemId: 'canola-oil', quantity: '1', unitType: 'case' },
      { itemId: 'pan-spray', quantity: '1', unitType: 'case' },
      { itemId: 'fryer-oil-olitalia', quantity: '3', unitType: 'case' },
      { itemId: 'salt-maldon', quantity: '1', unitType: 'tub' },
      { itemId: 'mascarpone', quantity: '1', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '1', unitType: 'case' },
      { itemId: 'milk-whole', quantity: '6', unitType: 'gallon' },
      { itemId: 'heavy-cream', quantity: '1', unitType: 'case' },
      { itemId: 'buttermilk', quantity: '2', unitType: 'pc' },
      { itemId: 'eggs-pasteurized', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2025-11-17',
    deliveryDate: '2025-11-19',
    items: [
      { itemId: 'flour-00', quantity: '1', unitType: 'bag' },
      { itemId: 'canola-oil', quantity: '1', unitType: 'case' },
      { itemId: 'fryer-oil-olitalia', quantity: '3', unitType: 'case' },
      { itemId: 'mustard-dijon', quantity: '1', unitType: 'tub' },
      { itemId: 'nuts-pistachio', quantity: '4', unitType: '#' },
      { itemId: 'chickpeas-dried', quantity: '1', unitType: 'case' },
      { itemId: 'rice-basmati', quantity: '1', unitType: 'bag' },
      { itemId: 'salt-kosher-crystal-diamond', quantity: '1', unitType: 'case' },
      { itemId: 'spice-black-pepper-whole', quantity: '2', unitType: 'pc' },
      { itemId: 'mascarpone', quantity: '1', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '1', unitType: 'case' },
      { itemId: 'milk-whole', quantity: '4', unitType: 'gallon' },
      { itemId: 'heavy-cream', quantity: '1', unitType: 'case' },
      { itemId: 'buttermilk', quantity: '2', unitType: 'pc' },
      { itemId: 'eggs-pasteurized', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2025-11-24',
    deliveryDate: '2025-11-26',
    items: [
      { itemId: 'flour-00', quantity: '1', unitType: 'bag' },
      { itemId: 'fryer-oil-olitalia', quantity: '4', unitType: 'case' },
      { itemId: 'spice-black-pepper-whole', quantity: '2', unitType: 'pc' },
      { itemId: 'butter-plugra', quantity: '1', unitType: 'case' },
      { itemId: 'milk-whole', quantity: '4', unitType: 'gallon' },
      { itemId: 'heavy-cream', quantity: '1', unitType: 'case' },
      { itemId: 'eggs-pasteurized', quantity: '1', unitType: 'case' },
      { itemId: 'tomato-paste-mutti', quantity: '1', unitType: 'case' },
      { itemId: 'spice-cinnamon-sticks', quantity: '3', unitType: 'pc' },
    ],
  },
  {
    date: '2025-12-01',
    deliveryDate: '2025-12-03',
    items: [
      { itemId: 'flour-00', quantity: '1', unitType: 'bag' },
      { itemId: 'flour-durum', quantity: '1', unitType: 'bag' },
      { itemId: 'sugar-granulated', quantity: '1', unitType: 'bag' },
      { itemId: 'fryer-oil-olitalia', quantity: '3', unitType: 'case' },
      { itemId: 'nuts-pistachio', quantity: '4', unitType: '#' },
      { itemId: 'nuts-walnuts', quantity: '4', unitType: '#' },
      { itemId: 'salt-kosher-crystal-diamond', quantity: '1', unitType: 'case' },
      { itemId: 'mascarpone', quantity: '1', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '1', unitType: 'case' },
      { itemId: 'milk-whole', quantity: '8', unitType: 'gallon' },
      { itemId: 'heavy-cream', quantity: '1', unitType: 'case' },
      { itemId: 'buttermilk', quantity: '2', unitType: 'pc' },
      { itemId: 'eggs-pasteurized', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2025-12-08',
    deliveryDate: '2025-12-10',
    items: [
      { itemId: 'cocoa-powder', quantity: '1', unitType: 'case' },
      { itemId: 'cornstarch', quantity: '1', unitType: 'case' },
      { itemId: 'fryer-oil-olitalia', quantity: '2', unitType: 'case' },
      { itemId: 'gelatin-sheets', quantity: '1', unitType: 'box' },
      { itemId: 'spice-cumin-seeds', quantity: '1', unitType: 'pc' },
      { itemId: 'penne', quantity: '1', unitType: 'bag' },
      { itemId: 'salt-maldon', quantity: '1', unitType: 'tub' },
      { itemId: 'mascarpone', quantity: '1', unitType: 'case' },
      { itemId: 'milk-whole', quantity: '2', unitType: 'gallon' },
      { itemId: 'heavy-cream', quantity: '1', unitType: 'case' },
      { itemId: 'buttermilk', quantity: '1', unitType: 'pc' },
      { itemId: 'eggs-pasteurized', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2026-01-04',
    deliveryDate: '2026-01-06',
    items: [
      { itemId: 'flour-00', quantity: '1', unitType: 'bag' },
      { itemId: 'canola-oil', quantity: '1', unitType: 'case' },
      { itemId: 'salt-kosher-crystal-diamond', quantity: '1', unitType: 'case' },
      { itemId: 'cornstarch', quantity: '1', unitType: 'case' },
      { itemId: 'spice-black-pepper-whole', quantity: '2', unitType: 'pc' },
      { itemId: 'spice-coriander-seeds', quantity: '1', unitType: 'pc' },
      { itemId: 'nuts-pistachio', quantity: '4', unitType: '#' },
      { itemId: 'milk-whole', quantity: '4', unitType: 'gallon' },
      { itemId: 'heavy-cream', quantity: '2', unitType: 'case' },
      { itemId: 'mascarpone', quantity: '1', unitType: 'case' },
      { itemId: 'buttermilk', quantity: '2', unitType: 'pc' },
      { itemId: 'eggs-pasteurized', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2026-01-12',
    deliveryDate: '2026-01-14',
    items: [
      { itemId: 'flour-00', quantity: '1', unitType: 'bag' },
      { itemId: 'penne', quantity: '1', unitType: 'bag' },
      { itemId: 'rice-basmati', quantity: '1', unitType: 'bag' },
      { itemId: 'nuts-pistachio', quantity: '4', unitType: '#' },
      { itemId: 'milk-whole', quantity: '4', unitType: 'gallon' },
      { itemId: 'heavy-cream', quantity: '1', unitType: 'case' },
      { itemId: 'mascarpone', quantity: '1', unitType: 'case' },
      { itemId: 'buttermilk', quantity: '2', unitType: 'pc' },
      { itemId: 'eggs-pasteurized', quantity: '1', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2026-01-19',
    deliveryDate: '2026-01-21',
    items: [
      { itemId: 'flour-00', quantity: '1', unitType: 'bag' },
      { itemId: 'flour-durum', quantity: '1', unitType: 'bag' },
      { itemId: 'sugar-granulated', quantity: '1', unitType: 'bag' },
      { itemId: 'fennel-pollen', quantity: '1', unitType: 'pc' },
      { itemId: 'salt-kosher-crystal-diamond', quantity: '1', unitType: 'case' },
      { itemId: 'rice-basmati', quantity: '1', unitType: 'bag' },
      { itemId: 'spice-black-pepper-whole', quantity: '3', unitType: 'pc' },
      { itemId: 'spice-cumin-seeds', quantity: '1', unitType: 'pc' },
      { itemId: 'nuts-pistachio', quantity: '4', unitType: '#' },
      { itemId: 'milk-whole', quantity: '8', unitType: 'gallon' },
      { itemId: 'heavy-cream', quantity: '1', unitType: 'case' },
      { itemId: 'mascarpone', quantity: '1', unitType: 'case' },
      { itemId: 'eggs-pasteurized', quantity: '1', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '2', unitType: 'case' },
      { itemId: 'tomato-paste-mutti', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2026-01-26',
    deliveryDate: '2026-01-28',
    items: [
      { itemId: 'flour-00', quantity: '1', unitType: 'bag' },
      { itemId: 'salt-kosher-crystal-diamond', quantity: '1', unitType: 'case' },
      { itemId: 'rice-basmati', quantity: '1', unitType: 'bag' },
      { itemId: 'nuts-walnuts', quantity: '4', unitType: '#' },
      { itemId: 'milk-whole', quantity: '4', unitType: 'gallon' },
      { itemId: 'buttermilk', quantity: '2', unitType: 'pc' },
      { itemId: 'heavy-cream', quantity: '1', unitType: 'case' },
      { itemId: 'eggs-pasteurized', quantity: '1', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '1', unitType: 'case' },
      { itemId: 'canola-oil', quantity: '1', unitType: 'case' },
      { itemId: 'cornstarch', quantity: '1', unitType: 'case' },
      { itemId: 'mustard-dijon', quantity: '1', unitType: 'tub' },
      { itemId: 'panko', quantity: '1', unitType: 'bag' },
      { itemId: 'spice-cinnamon-sticks', quantity: '1', unitType: 'pc' },
    ],
  },
  {
    date: '2026-02-01',
    deliveryDate: '2026-02-02',
    items: [
      { itemId: 'flour-00', quantity: '1', unitType: 'bag' },
      { itemId: 'flour-durum', quantity: '1', unitType: 'bag' },
      { itemId: 'sugar-granulated', quantity: '1', unitType: 'bag' },
      { itemId: 'rice-basmati', quantity: '1', unitType: 'bag' },
      { itemId: 'spice-black-pepper-whole', quantity: '2', unitType: 'pc' },
      { itemId: 'nuts-pistachio', quantity: '4', unitType: '#' },
      { itemId: 'milk-whole', quantity: '6', unitType: 'gallon' },
      { itemId: 'buttermilk', quantity: '2', unitType: 'pc' },
      { itemId: 'heavy-cream', quantity: '1', unitType: 'case' },
      { itemId: 'eggs-pasteurized', quantity: '1', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '2', unitType: 'case' },
      { itemId: 'mascarpone', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2026-02-09',
    deliveryDate: '2026-02-10',
    items: [
      { itemId: 'flour-00', quantity: '1', unitType: 'bag' },
      { itemId: 'rice-basmati', quantity: '1', unitType: 'bag' },
      { itemId: 'salt-kosher-crystal-diamond', quantity: '1', unitType: 'case' },
      { itemId: 'cornstarch', quantity: '1', unitType: 'case' },
      { itemId: 'fennel-pollen', quantity: '1', unitType: 'pc' },
      { itemId: 'chickpeas-dried', quantity: '1', unitType: 'case' },
      { itemId: 'penne', quantity: '1', unitType: 'bag' },
      { itemId: 'spice-cinnamon-sticks', quantity: '5', unitType: 'pc' },
      { itemId: 'spice-fennel-seed', quantity: '2', unitType: 'pc' },
      { itemId: 'spice-coriander-seeds', quantity: '2', unitType: 'pc' },
      { itemId: 'spice-cumin-seeds', quantity: '2', unitType: 'pc' },
      { itemId: 'nuts-pistachio', quantity: '4', unitType: '#' },
      { itemId: 'nuts-walnuts', quantity: '4', unitType: '#' },
      { itemId: 'milk-whole', quantity: '8', unitType: 'gallon' },
      { itemId: 'buttermilk', quantity: '6', unitType: 'pc' },
      { itemId: 'heavy-cream', quantity: '2', unitType: 'case' },
      { itemId: 'eggs-pasteurized', quantity: '2', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '1', unitType: 'case' },
      { itemId: 'mascarpone', quantity: '3', unitType: 'case' },
      { itemId: 'tamari', quantity: '1', unitType: 'pc' },
    ],
  },
  {
    date: '2026-02-16',
    deliveryDate: '2026-02-17',
    items: [
      { itemId: 'flour-00', quantity: '1', unitType: 'bag' },
      { itemId: 'flour-durum', quantity: '1', unitType: 'bag' },
      { itemId: 'sugar-granulated', quantity: '1', unitType: 'bag' },
      { itemId: 'canola-oil', quantity: '2', unitType: 'case' },
      { itemId: 'cocoa-powder', quantity: '1', unitType: 'case' },
      { itemId: 'pan-spray', quantity: '1', unitType: 'case' },
      { itemId: 'rice-basmati', quantity: '1', unitType: 'bag' },
      { itemId: 'salt-kosher-crystal-diamond', quantity: '1', unitType: 'case' },
      { itemId: 'spice-black-pepper-whole', quantity: '2', unitType: 'pc' },
      { itemId: 'vinegar-balsamic', quantity: '1', unitType: 'pc' },
      { itemId: 'nuts-walnuts', quantity: '4', unitType: '#' },
      { itemId: 'milk-whole', quantity: '8', unitType: 'gallon' },
      { itemId: 'buttermilk', quantity: '3', unitType: 'pc' },
      { itemId: 'heavy-cream', quantity: '2', unitType: 'case' },
      { itemId: 'eggs-pasteurized', quantity: '1', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2026-02-23',
    deliveryDate: '2026-02-24',
    items: [
      { itemId: 'flour-00', quantity: '2', unitType: 'bag' },
      { itemId: 'sugar-granulated', quantity: '1', unitType: 'bag' },
      { itemId: 'cornstarch', quantity: '1', unitType: 'case' },
      { itemId: 'salt-kosher-crystal-diamond', quantity: '1', unitType: 'case' },
      { itemId: 'spice-black-pepper-whole', quantity: '2', unitType: 'pc' },
      { itemId: 'mustard-dijon', quantity: '1', unitType: 'tub' },
      { itemId: 'penne', quantity: '1', unitType: 'bag' },
      { itemId: 'salt-maldon', quantity: '1', unitType: 'tub' },
      { itemId: 'spice-cinnamon-sticks', quantity: '4', unitType: 'pc' },
      { itemId: 'tomato-paste-mutti', quantity: '2', unitType: 'case' },
      { itemId: 'nuts-pistachio', quantity: '4', unitType: '#' },
      { itemId: 'nuts-walnuts', quantity: '4', unitType: '#' },
      { itemId: 'milk-whole', quantity: '8', unitType: 'gallon' },
      { itemId: 'buttermilk', quantity: '3', unitType: 'pc' },
      { itemId: 'heavy-cream', quantity: '1', unitType: 'case' },
      { itemId: 'eggs-pasteurized', quantity: '1', unitType: 'case' },
      { itemId: 'mascarpone', quantity: '1', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2026-03-02',
    deliveryDate: '2026-03-03',
    items: [
      { itemId: 'flour-00', quantity: '1', unitType: 'bag' },
      { itemId: 'flour-durum', quantity: '1', unitType: 'bag' },
      { itemId: 'salt-kosher-crystal-diamond', quantity: '1', unitType: 'case' },
      { itemId: 'nuts-walnuts', quantity: '4', unitType: '#' },
      { itemId: 'canola-oil', quantity: '1', unitType: 'case' },
      { itemId: 'rice-basmati', quantity: '1', unitType: 'bag' },
      { itemId: 'milk-whole', quantity: '5', unitType: 'gallon' },
      { itemId: 'buttermilk', quantity: '4', unitType: 'pc' },
      { itemId: 'heavy-cream', quantity: '2', unitType: 'case' },
      { itemId: 'eggs-pasteurized', quantity: '1', unitType: 'case' },
      { itemId: 'mascarpone', quantity: '1', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2026-03-09',
    deliveryDate: '2026-03-10',
    items: [
      { itemId: 'flour-00', quantity: '1', unitType: 'bag' },
      { itemId: 'flour-durum', quantity: '1', unitType: 'bag' },
      { itemId: 'nuts-pistachio', quantity: '4', unitType: '#' },
      { itemId: 'canola-oil', quantity: '1', unitType: 'case' },
      { itemId: 'spice-cinnamon-sticks', quantity: '3', unitType: 'pc' },
      { itemId: 'rice-basmati', quantity: '1', unitType: 'bag' },
      { itemId: 'milk-whole', quantity: '7', unitType: 'gallon' },
      { itemId: 'buttermilk', quantity: '2', unitType: 'pc' },
      { itemId: 'heavy-cream', quantity: '2', unitType: 'case' },
      { itemId: 'eggs-pasteurized', quantity: '1', unitType: 'case' },
      { itemId: 'mascarpone', quantity: '1', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2026-03-16',
    deliveryDate: '2026-03-17',
    items: [
      { itemId: 'flour-00', quantity: '1', unitType: 'bag' },
      { itemId: 'flour-durum', quantity: '1', unitType: 'bag' },
      { itemId: 'sugar-granulated', quantity: '1', unitType: 'bag' },
      { itemId: 'chickpeas-dried', quantity: '1', unitType: 'case' },
      { itemId: 'cornstarch', quantity: '1', unitType: 'case' },
      { itemId: 'salt-kosher-crystal-diamond', quantity: '1', unitType: 'case' },
      { itemId: 'nuts-walnuts', quantity: '4', unitType: '#' },
      { itemId: 'canola-oil', quantity: '1', unitType: 'case' },
      { itemId: 'spice-cinnamon-sticks', quantity: '2', unitType: 'pc' },
      { itemId: 'spice-black-pepper-whole', quantity: '2', unitType: 'pc' },
      { itemId: 'penne', quantity: '1', unitType: 'bag' },
      { itemId: 'milk-whole', quantity: '6', unitType: 'gallon' },
      { itemId: 'buttermilk', quantity: '3', unitType: 'pc' },
      { itemId: 'heavy-cream', quantity: '1', unitType: 'case' },
      { itemId: 'eggs-pasteurized', quantity: '1', unitType: 'case' },
      { itemId: 'mascarpone', quantity: '1', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2026-03-23',
    deliveryDate: '2026-03-24',
    items: [
      { itemId: 'flour-00', quantity: '2', unitType: 'bag' },
      { itemId: 'cornstarch', quantity: '1', unitType: 'case' },
      { itemId: 'salt-kosher-crystal-diamond', quantity: '1', unitType: 'case' },
      { itemId: 'rice-basmati', quantity: '2', unitType: 'bag' },
      { itemId: 'spice-cinnamon-sticks', quantity: '3', unitType: 'pc' },
      { itemId: 'sugar-light-brown', quantity: '3', unitType: 'bag' },
      { itemId: 'tomato-paste-mutti', quantity: '1', unitType: 'case' },
      { itemId: 'milk-whole', quantity: '7', unitType: 'gallon' },
      { itemId: 'buttermilk', quantity: '3', unitType: 'pc' },
      { itemId: 'heavy-cream', quantity: '2', unitType: 'case' },
      { itemId: 'eggs-pasteurized', quantity: '1', unitType: 'case' },
      { itemId: 'mascarpone', quantity: '1', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '1', unitType: 'case' },
    ],
  },
  {
    date: '2026-03-30',
    deliveryDate: '2026-03-31',
    items: [
      { itemId: 'flour-00', quantity: '1', unitType: 'bag' },
      { itemId: 'salt-kosher-crystal-diamond', quantity: '1', unitType: 'case' },
      { itemId: 'salt-maldon', quantity: '1', unitType: 'tub' },
      { itemId: 'sugar-light-brown', quantity: '1', unitType: 'bag' },
      { itemId: 'cocoa-powder', quantity: '1', unitType: 'case' },
      { itemId: 'nuts-pistachio', quantity: '4', unitType: '#' },
      { itemId: 'fryer-oil-olitalia', quantity: '3', unitType: 'case' },
      { itemId: 'spice-cinnamon-sticks', quantity: '2', unitType: 'pc' },
      { itemId: 'rice-basmati', quantity: '1', unitType: 'bag' },
      { itemId: 'milk-whole', quantity: '7', unitType: 'gallon' },
      { itemId: 'buttermilk', quantity: '2', unitType: 'pc' },
      { itemId: 'heavy-cream', quantity: '1', unitType: 'case' },
      { itemId: 'eggs-pasteurized', quantity: '1', unitType: 'case' },
      { itemId: 'mascarpone', quantity: '1', unitType: 'case' },
      { itemId: 'butter-plugra', quantity: '1', unitType: 'case' },
      { itemId: 'cornmeal', quantity: '5', unitType: '#' },
    ],
  },
]

export const aceEndicoSeedHistory = buildVendorHistoryFromSource('ace-endico', {
  kind: 'structured_orders',
  orders: aceEndicoMessageHistoryRaw,
})
