import type { VendorCatalogSheetRow } from '../shared/vendorData/types'

/**
 * Ace / Endico section from Dry Goods sheet + normalized aliases seen in chat history.
 */
export const aceEndicoDryGoodsSheetRows: VendorCatalogSheetRow[] = [
  { id: 'flour-00', name: "Flour - '00'", unitType: 'bag' },
  { id: 'flour-durum', name: 'Flour - Durum', unitType: 'bag' },
  { id: 'fryer-oil-olitalia', name: 'Fryer Oil - Olitalia', unitType: 'case' },
  { id: 'canola-oil', name: 'Canola Oil', unitType: 'case' },
  { id: 'chickpeas-dried', name: 'Chickpeas - Dried', unitType: 'case' },
  { id: 'chocolate-callebaut-milk', name: 'Chocolate - Callebaut Milk', unitType: 'bag' },
  { id: 'cocoa-powder', name: 'Cocoa Powder', unitType: 'case' },
  { id: 'cornstarch', name: 'Cornstarch', unitType: 'case' },
  { id: 'cornmeal', name: 'Cornmeal', unitType: '#' },
  { id: 'fennel-pollen', name: 'Fennel Pollen', unitType: 'pc' },
  { id: 'mustard-dijon', name: 'Mustard - Dijon', unitType: 'tub' },
  { id: 'gelatin-sheets', name: 'Gelatin Sheets', unitType: 'box' },
  { id: 'nuts-pistachio', name: 'Nuts - Pistachio', unitType: '#' },
  { id: 'nuts-walnuts', name: 'Nuts - Walnuts', unitType: '#' },
  { id: 'nuts-hazelnuts', name: 'Nuts - Hazelnuts', unitType: '#' },
  { id: 'pan-spray', name: 'Pan Spray', unitType: 'case' },
  { id: 'panko', name: 'Panko', unitType: 'bag' },
  { id: 'penne', name: 'Penne', unitType: 'bag' },
  { id: 'rice-basmati', name: 'Rice, Basmati', unitType: 'bag' },
  { id: 'salt-kosher-crystal-diamond', name: 'Salt - Kosher Crystal Diamond', unitType: 'case' },
  { id: 'salt-maldon', name: 'Salt - Maldon', unitType: 'tub' },
  { id: 'spice-black-pepper-whole', name: 'Spices - Black Pepper - Whole', unitType: 'pc' },
  { id: 'spice-cinnamon-sticks', name: 'Spices - Cinnamon Sticks', unitType: 'pc' },
  { id: 'spice-coriander-seeds', name: 'Spices - Coriander Seeds', unitType: 'pc' },
  { id: 'spice-cumin-seeds', name: 'Spices - Cumin Seeds', unitType: 'pc' },
  { id: 'spice-fennel-seed', name: 'Spices - Fennel Seed', unitType: 'pc' },
  { id: 'spice-garlic-powder', name: 'Spices - Garlic Powder', unitType: 'pc' },
  { id: 'sugar-confectioners-10x', name: 'Sugar - Confectioners / 10X', unitType: 'case' },
  { id: 'sugar-granulated', name: 'Sugar - Granulated', unitType: 'bag' },
  { id: 'sugar-light-brown', name: 'Sugar - Light Brown', unitType: 'bag' },
  { id: 'tamari', name: 'Tamari', unitType: 'pc' },
  { id: 'tomato-paste-mutti', name: 'Tomato Paste - Mutti', unitType: 'case' },
  { id: 'vinegar-balsamic', name: 'Vinegar, Balsamic', unitType: 'pc' },
  { id: 'vinegar-champagne', name: 'Vinegar, Champagne', unitType: 'pc' },
  { id: 'vinegar-red-wine', name: 'Vinegar, Red Wine', unitType: 'pc' },
  { id: 'vinegar-cider', name: 'Vinegar, Cider', unitType: 'pc' },
  { id: 'milk-whole', name: 'Milk, Whole', unitType: 'gallon' },
  { id: 'heavy-cream', name: 'Heavy Cream', unitType: 'case' },
  { id: 'buttermilk', name: 'Buttermilk', unitType: 'pc' },
  { id: 'butter-plugra', name: 'Butter, European (Plugra)', unitType: 'case' },
  { id: 'mascarpone', name: 'Mascarpone', unitType: 'case' },
  { id: 'eggs-pasteurized', name: 'Eggs, Pasteurized', unitType: 'case' },
]
